import { CatalogoItem } from 'src/app/componentes/rips/rips.model';

export const RIPS_PAISES: CatalogoItem[] = [
  { id: 'AFG', nombre: 'AFGHANISTAN' },
  { id: 'ALA', nombre: 'ÅLAND ISLANDS' },
  { id: 'ALB', nombre: 'ALBANIA' },
  { id: 'DZA', nombre: 'ALGERIA' },
  { id: 'ASM', nombre: 'AMERICAN SAMOA' },
  { id: 'AND', nombre: 'ANDORRA' },
  { id: 'AGO', nombre: 'ANGOLA' },
  { id: 'AIA', nombre: 'ANGUILLA' },
  { id: 'ATG', nombre: 'ANTIGUA AND BARBUDA' },
  { id: 'ARG', nombre: 'ARGENTINA' },
  { id: 'ARM', nombre: 'ARMENIA' },
  { id: 'ABW', nombre: 'ARUBA' },
  { id: 'AUS', nombre: 'AUSTRALIA' },
  { id: 'AUT', nombre: 'AUSTRIA' },
  { id: 'AZE', nombre: 'AZERBAIJAN' },
  { id: 'BHS', nombre: 'BAHAMAS' },
  { id: 'BHR', nombre: 'BAHRAIN' },
  { id: 'BGD', nombre: 'BANGLADESH' },
  { id: 'BRB', nombre: 'BARBADOS' },
  { id: 'BLR', nombre: 'BELARUS' },
  { id: 'BEL', nombre: 'BELGIUM' },
  { id: 'BLZ', nombre: 'BELIZE' },
  { id: 'BEN', nombre: 'BENIN' },
  { id: 'BMU', nombre: 'BERMUDA' },
  { id: 'BTN', nombre: 'BHUTAN' },
  { id: 'BOL', nombre: 'BOLIVIA' },
  { id: 'BIH', nombre: 'BOSNIA AND HERZEGOVINA' },
  { id: 'BWA', nombre: 'BOTSWANA' },
  { id: 'BRA', nombre: 'BRAZIL' },
  { id: 'VGB', nombre: 'BRITISH VIRGIN ISLANDS' },
  { id: 'BRN', nombre: 'BRUNEI DARUSSALAM' },
  { id: 'BGR', nombre: 'BULGARIA' },
  { id: 'BFA', nombre: 'BURKINA FASO' },
  { id: 'BDI', nombre: 'BURUNDI' },
  { id: 'KHM', nombre: 'CAMBODIA' },
  { id: 'CMR', nombre: 'CAMEROON' },
  { id: 'CAN', nombre: 'CANADA' },
  { id: 'CPV', nombre: 'CAPE VERDE' },
  { id: 'CYM', nombre: 'CAYMAN ISLANDS' },
  { id: 'CAF', nombre: 'CENTRAL AFRICAN REPUBLIC' },
  { id: 'TCD', nombre: 'CHAD' },
  { id: 'CHL', nombre: 'CHILE' },
  { id: 'CHN', nombre: 'CHINA' },
  {
    id: 'HKG',
    nombre: 'HONG KONG SPECIAL ADMINISTRATIVE REGION OF CHINA',
  },
  {
    id: 'MAC',
    nombre: 'MACAO SPECIAL ADMINISTRATIVE REGION OF CHINA',
  },
  { id: 'COL', nombre: 'COLOMBIA' },
  { id: 'COM', nombre: 'COMOROS' },
  { id: 'COG', nombre: 'CONGO' },
  { id: 'COK', nombre: 'COOK ISLANDS' },
  { id: 'CRI', nombre: 'COSTA RICA' },
  { id: 'CIV', nombre: "CÔTE D'IVOIRE" },
  { id: 'HRV', nombre: 'CROATIA' },
  { id: 'CUB', nombre: 'CUBA' },
  { id: 'CYP', nombre: 'CYPRUS' },
  { id: 'CZE', nombre: 'CZECH REPUBLIC' },
  { id: 'PRK', nombre: "DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA" },
  { id: 'COD', nombre: 'DEMOCRATIC REPUBLIC OF THE CONGO' },
  { id: 'DNK', nombre: 'DENMARK' },
  { id: 'DJI', nombre: 'DJIBOUTI' },
  { id: 'DMA', nombre: 'DOMINICA' },
  { id: 'DOM', nombre: 'DOMINICAN REPUBLIC' },
  { id: 'ECU', nombre: 'ECUADOR' },
  { id: 'EGY', nombre: 'EGYPT' },
  { id: 'SLV', nombre: 'EL SALVADOR' },
  { id: 'GNQ', nombre: 'EQUATORIAL GUINEA' },
  { id: 'ERI', nombre: 'ERITREA' },
  { id: 'EST', nombre: 'ESTONIA' },
  { id: 'ETH', nombre: 'ETHIOPIA' },
  { id: 'FRO', nombre: 'FAEROE ISLANDS' },
  { id: 'FLK', nombre: 'FALKLAND ISLANDS (MALVINAS)' },
  { id: 'FJI', nombre: 'FIJI' },
  { id: 'FIN', nombre: 'FINLAND' },
  { id: 'FRA', nombre: 'FRANCE' },
  { id: 'GUF', nombre: 'FRENCH GUIANA' },
  { id: 'PYF', nombre: 'FRENCH POLYNESIA' },
  { id: 'GAB', nombre: 'GABON' },
  { id: 'GMB', nombre: 'GAMBIA' },
  { id: 'GEO', nombre: 'GEORGIA' },
  { id: 'DEU', nombre: 'GERMANY' },
  { id: 'GHA', nombre: 'GHANA' },
  { id: 'GIB', nombre: 'GIBRALTAR' },
  { id: 'GRC', nombre: 'GREECE' },
  { id: 'GRL', nombre: 'GREENLAND' },
  { id: 'GRD', nombre: 'GRENADA' },
  { id: 'GLP', nombre: 'GUADELOUPE' },
  { id: 'GUM', nombre: 'GUAM' },
  { id: 'GTM', nombre: 'GUATEMALA' },
  { id: 'GGY', nombre: 'GUERNSEY' },
  { id: 'GIN', nombre: 'GUINEA' },
  { id: 'GNB', nombre: 'GUINEA-BISSAU' },
  { id: 'GUY', nombre: 'GUYANA' },
  { id: 'HTI', nombre: 'HAITI' },
  { id: 'VAT', nombre: 'HOLY SEE' },
  { id: 'HND', nombre: 'HONDURAS' },
  { id: 'HUN', nombre: 'HUNGARY' },
  { id: 'ISL', nombre: 'ICELAND' },
  { id: 'IND', nombre: 'INDIA' },
  { id: 'IDN', nombre: 'INDONESIA' },
  { id: 'IRN', nombre: 'IRAN, ISLAMIC REPUBLIC OF' },
  { id: 'IRQ', nombre: 'IRAQ' },
  { id: 'IRL', nombre: 'IRELAND' },
  { id: 'IMN', nombre: 'ISLE OF MAN' },
  { id: 'ISR', nombre: 'ISRAEL' },
  { id: 'ITA', nombre: 'ITALY' },
  { id: 'JAM', nombre: 'JAMAICA' },
  { id: 'JPN', nombre: 'JAPAN' },
  { id: 'JEY', nombre: 'JERSEY' },
  { id: 'JOR', nombre: 'JORDAN' },
  { id: 'KAZ', nombre: 'KAZAKHSTAN' },
  { id: 'KEN', nombre: 'KENYA' },
  { id: 'KIR', nombre: 'KIRIBATI' },
  { id: 'KWT', nombre: 'KUWAIT' },
  { id: 'KGZ', nombre: 'KYRGYZSTAN' },
  { id: 'LAO', nombre: "LAO PEOPLE'S DEMOCRATIC REPUBLIC" },
  { id: 'LVA', nombre: 'LATVIA' },
  { id: 'LBN', nombre: 'LEBANON' },
  { id: 'LSO', nombre: 'LESOTHO' },
  { id: 'LBR', nombre: 'LIBERIA' },
  { id: 'LBY', nombre: 'LIBYAN ARAB JAMAHIRIYA' },
  { id: 'LIE', nombre: 'LIECHTENSTEIN' },
  { id: 'LTU', nombre: 'LITHUANIA' },
  { id: 'LUX', nombre: 'LUXEMBOURG' },
  { id: 'MDG', nombre: 'MADAGASCAR' },
  { id: 'MWI', nombre: 'MALAWI' },
  { id: 'MYS', nombre: 'MALAYSIA' },
  { id: 'MDV', nombre: 'MALDIVES' },
  { id: 'MLI', nombre: 'MALI' },
  { id: 'MLT', nombre: 'MALTA' },
  { id: 'MHL', nombre: 'MARSHALL ISLANDS' },
  { id: 'MTQ', nombre: 'MARTINIQUE' },
  { id: 'MRT', nombre: 'MAURITANIA' },
  { id: 'MUS', nombre: 'MAURITIUS' },
  { id: 'MYT', nombre: 'MAYOTTE' },
  { id: 'MEX', nombre: 'MEXICO' },
  { id: 'FSM', nombre: 'MICRONESIA, FEDERATED STATES OF' },
  { id: 'MDA', nombre: 'MOLDOVA' },
  { id: 'MCO', nombre: 'MONACO' },
  { id: 'MNG', nombre: 'MONGOLIA' },
  { id: 'MNE', nombre: 'MONTENEGRO' },
  { id: 'MSR', nombre: 'MONTSERRAT' },
  { id: 'MAR', nombre: 'MOROCCO' },
  { id: 'MOZ', nombre: 'MOZAMBIQUE' },
  { id: 'MMR', nombre: 'MYANMAR' },
  { id: 'NAM', nombre: 'NAMIBIA' },
  { id: 'NRU', nombre: 'NAURU' },
  { id: 'NPL', nombre: 'NEPAL' },
  { id: 'NLD', nombre: 'NETHERLANDS' },
  { id: 'ANT', nombre: 'NETHERLANDS ANTILLES' },
  { id: 'NCL', nombre: 'NEW CALEDONIA' },
  { id: 'NZL', nombre: 'NEW ZEALAND' },
  { id: 'NIC', nombre: 'NICARAGUA' },
  { id: 'NER', nombre: 'NIGER' },
  { id: 'NGA', nombre: 'NIGERIA' },
  { id: 'NIU', nombre: 'NIUE' },
  { id: 'NFK', nombre: 'NORFOLK ISLAND' },
  { id: 'MNP', nombre: 'NORTHERN MARIANA ISLANDS' },
  { id: 'NOR', nombre: 'NORWAY' },
  { id: 'PSE', nombre: 'OCCUPIED PALESTINIAN TERRITORY' },
  { id: 'OMN', nombre: 'OMAN' },
  { id: 'PAK', nombre: 'PAKISTAN' },
  { id: 'PLW', nombre: 'PALAU' },
  { id: 'PAN', nombre: 'PANAMA' },
  { id: 'PNG', nombre: 'PAPUA NEW GUINEA' },
  { id: 'PRY', nombre: 'PARAGUAY' },
  { id: 'PER', nombre: 'PERU' },
  { id: 'PHL', nombre: 'PHILIPPINES' },
  { id: 'PCN', nombre: 'PITCAIRN' },
  { id: 'POL', nombre: 'POLAND' },
  { id: 'PRT', nombre: 'PORTUGAL' },
  { id: 'PRI', nombre: 'PUERTO RICO' },
  { id: 'QAT', nombre: 'QATAR' },
  { id: 'KOR', nombre: 'REPUBLIC OF KOREA' },
  { id: 'REU', nombre: 'R_UNION' },
  { id: 'ROU', nombre: 'ROMANIA' },
  { id: 'RUS', nombre: 'RUSSIAN FEDERATION' },
  { id: 'RWA', nombre: 'RWANDA' },
  { id: 'BLM', nombre: 'SAINT-BARTHÉLEMY' },
  { id: 'SHN', nombre: 'SAINT HELENA' },
  { id: 'KNA', nombre: 'SAINT KITTS AND NEVIS' },
  { id: 'LCA', nombre: 'SAINT LUCIA' },
  { id: 'MAF', nombre: 'SAINT-MARTIN (FRENCH PART)' },
  { id: 'SPM', nombre: 'SAINT PIERRE AND MIQUELON' },
  { id: 'VCT', nombre: 'SAINT VINCENT AND THE GRENADINES' },
  { id: 'WSM', nombre: 'SAMOA' },
  { id: 'SMR', nombre: 'SAN MARINO' },
  { id: 'STP', nombre: 'SAO TOME AND PRINCIPE' },
  { id: 'SAU', nombre: 'SAUDI ARABIA' },
  { id: 'SEN', nombre: 'SENEGAL' },
  { id: 'SRB', nombre: 'SERBIA' },
  { id: 'SYC', nombre: 'SEYCHELLES' },
  { id: 'SLE', nombre: 'SIERRA LEONE' },
  { id: 'SGP', nombre: 'SINGAPORE' },
  { id: 'SVK', nombre: 'SLOVAKIA' },
  { id: 'SVN', nombre: 'SLOVENIA' },
  { id: 'SLB', nombre: 'SOLOMON ISLANDS' },
  { id: 'SOM', nombre: 'SOMALIA' },
  { id: 'ZAF', nombre: 'SOUTH AFRICA' },
  { id: 'ESP', nombre: 'SPAIN' },
  { id: 'LKA', nombre: 'SRI LANKA' },
  { id: 'SDN', nombre: 'SUDAN' },
  { id: 'SUR', nombre: 'SURINAME' },
  { id: 'SJM', nombre: 'SVALBARD AND JAN MAYEN ISLANDS' },
  { id: 'SWZ', nombre: 'SWAZILAND' },
  { id: 'SWE', nombre: 'SWEDEN' },
  { id: 'CHE', nombre: 'SWITZERLAND' },
  { id: 'SYR', nombre: 'SYRIAN ARAB REPUBLIC' },
  { id: 'TJK', nombre: 'TAJIKISTAN' },
  { id: 'THA', nombre: 'THAILAND' },
  { id: 'MKD', nombre: 'THE FORMER YUGOSLAV REPUBLIC OF MACEDONIA' },
  { id: 'TLS', nombre: 'TIMOR-LESTE' },
  { id: 'TGO', nombre: 'TOGO' },
  { id: 'TKL', nombre: 'TOKELAU' },
  { id: 'TON', nombre: 'TONGA' },
  { id: 'TTO', nombre: 'TRINIDAD AND TOBAGO' },
  { id: 'TUN', nombre: 'TUNISIA' },
  { id: 'TUR', nombre: 'TURKEY' },
  { id: 'TKM', nombre: 'TURKMENISTAN' },
  { id: 'TCA', nombre: 'TURKS AND CAICOS ISLANDS' },
  { id: 'TUV', nombre: 'TUVALU' },
  { id: 'UGA', nombre: 'UGANDA' },
  { id: 'UKR', nombre: 'UKRAINE' },
  { id: 'ARE', nombre: 'UNITED ARAB EMIRATES' },
  {
    id: 'GBR',
    nombre: 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND',
  },
  { id: 'TZA', nombre: 'UNITED REPUBLIC OF TANZANIA' },
  { id: 'USA', nombre: 'UNITED STATES OF AMERICA' },
  { id: 'VIR', nombre: 'UNITED STATES VIRGIN ISLANDS' },
  { id: 'URY', nombre: 'URUGUAY' },
  { id: 'UZB', nombre: 'UZBEKISTAN' },
  { id: 'VUT', nombre: 'VANUATU' },
  { id: 'VEN', nombre: 'VENEZUELA (BOLIVARIAN REPUBLIC OF)' },
  { id: 'VNM', nombre: 'VIET NAM' },
  { id: 'WLF', nombre: 'WALLIS AND FUTUNA ISLANDS' },
  { id: 'ESH', nombre: 'WESTERN SAHARA' },
  { id: 'YEM', nombre: 'YEMEN' },
  { id: 'ZMB', nombre: 'ZAMBIA' },
  { id: 'ZWE', nombre: 'ZIMBABWE' },
];

export const RIPS_SI_NO: CatalogoItem[] = [
  { id: 'NO', nombre: 'NO' },
  { id: 'SI', nombre: 'SI' },
];

export const RIPS_TIPOS_DIAGNOSTICO: CatalogoItem[] = [
  { id: '01', nombre: 'IMPRESIÓN DIAGNÓSTICA' },
  { id: '02', nombre: 'CONFIRMADO NUEVO' },
  { id: '03', nombre: 'CONFIRMADO REPETIDO' },
];

export const RIPS_FINALIDADES_CONSULTA: CatalogoItem[] = [
  {
    id: '11',
    nombre: 'VALORACION INTEGRAL PARA LA PROMOCION Y MANTENIMIENTO',
  },
  { id: '12', nombre: 'DETECCION TEMPRANA DE ENFERMEDAD GENERAL' },
  { id: '13', nombre: 'DETECCION TEMPRANA DE ENFERMEDAD LABORAL' },
  { id: '14', nombre: 'PROTECCION ESPECIFICA' },
  { id: '15', nombre: 'DIAGNOSTICO' },
  { id: '16', nombre: 'TRATAMIENTO' },
  { id: '17', nombre: 'REHABILITACION' },
  { id: '18', nombre: 'PALIACION' },
  { id: '19', nombre: 'PLANIFICACION FAMILIAR Y ANTICONCEPCION' },
  { id: '20', nombre: 'PROMOCION Y APOYO A LA LACTANCIA MATERNA' },
  { id: '21', nombre: 'ATENCION BASICA DE ORIENTACION FAMILIAR' },
  { id: '22', nombre: 'ATENCION PARA EL CUIDADO PRECONCEPCIONAL' },
  { id: '23', nombre: 'ATENCION PARA EL CUIDADO PRENATAL' },
  { id: '24', nombre: 'INTERRUPCION VOLUNTARIA DEL EMBARAZO' },
  { id: '25', nombre: 'ATENCION DEL PARTO Y PUERPERIO' },
  { id: '26', nombre: 'ATENCION PARA EL CUIDADO DEL RECIEN NACIDO' },
  { id: '27', nombre: 'ATENCION PARA EL SEGUIMIENTO DEL RECIEN NACIDO' },
  { id: '28', nombre: 'PREPARACION PARA LA MATERNIDAD Y LA PATERNIDAD' },
  { id: '29', nombre: 'PROMOCION DE ACTIVIDAD FISICA' },
  { id: '30', nombre: 'PROMOCION DE LA CESACION DEL TABAQUISMO' },
  { id: '31', nombre: 'PREVENCION DEL CONSUMO DE SUSTANCIAS PSICOACTIVAS' },
  { id: '32', nombre: 'PROMOCION DE LA ALIMENTACION SALUDABLE' },
  {
    id: '33',
    nombre:
      'PROMOCION PARA EL EJERCICIO DE LOS DERECHOS SEXUALES Y DERECHOS REPRODUCTIVOS',
  },
  {
    id: '34',
    nombre: 'PROMOCION PARA EL DESARROLLO DE HABILIDADES PARA LA VIDA',
  },
  {
    id: '35',
    nombre:
      'PROMOCION PARA LA CONSTRUCCION DE ESTRATEGIAS DE AFRONTAMIENTO FRENTE A SUCESOS VITALES',
  },
  { id: '36', nombre: 'PROMOCION DE LA SANA CONVIVENCIA Y EL TEJIDO SOCIAL' },
  {
    id: '37',
    nombre:
      'PROMOCION DE UN AMBIENTE SEGURO Y DE CUIDADO Y PROTECCION DEL AMBIENTE',
  },
  {
    id: '38',
    nombre:
      'PROMOCION DEL EMPODERAMIENTO PARA EL EJERCICIO DEL DERECHO A LA SALUD',
  },
  {
    id: '39',
    nombre:
      'PROMOCION PARA LA ADOPCION DE PRACTICAS DE CRIANZA Y CUIDADO PARA LA SALUD',
  },
  {
    id: '40',
    nombre: 'PROMOCION DE LA CAPACIDAD DE LA AGENCIA Y CUIDADO DE LA SALUD',
  },
  { id: '41', nombre: 'DESARROLLO DE HABILIDADES COGNITIVAS' },
  { id: '42', nombre: 'INTERVENCION COLECTIVA' },
  {
    id: '43',
    nombre: 'MODIFICACION DE LA ESTETICA CORPORAL FINES ESTETICOS',
  },
  { id: '44', nombre: 'OTRA' },
];

export const RIPS_CAUSAS_ATENCION: CatalogoItem[] = [
  { id: '21', nombre: 'ACCIDENTE DE TRABAJO' },
  { id: '22', nombre: 'ACCIDENTE EN EL HOGAR' },
  { id: '23', nombre: 'ACCIDENTE DE TRANSITO DE ORIGEN COMUN' },
  { id: '24', nombre: 'ACCIDENTE DE TRANSITO DE ORIGEN LABORAL' },
  { id: '25', nombre: 'ACCIDENTE EN EL ENTORNO EDUCATIVO' },
  { id: '26', nombre: 'OTRO TIPO DE ACCIDENTE' },
  { id: '27', nombre: 'EVENTO CATASTROFICO DE ORIGEN NATURAL' },
  { id: '28', nombre: 'LESION POR AGRESION' },
  { id: '29', nombre: 'LESION AUTO INFLIGIDA' },
  { id: '30', nombre: 'SOSPECHA DE VIOLENCIA FISICA' },
  { id: '31', nombre: 'SOSPECHA DE VIOLENCIA PSICOLOGICA' },
  { id: '32', nombre: 'SOSPECHA DE VIOLENCIA SEXUAL' },
  { id: '33', nombre: 'SOSPECHA DE NEGLIGENCIA Y ABANDONO' },
  {
    id: '34',
    nombre: 'IVE RELACIONADO CON PELIGRO A LA SALUD O VIDA DE LA MUJER',
  },
  {
    id: '35',
    nombre: 'IVE POR MALFORMACION CONGENITA INCOMPATIBLE CON LA VIDA',
  },
  {
    id: '36',
    nombre:
      'IVE POR VIOLENCIA SEXUAL, INCESTO O POR INSEMINACION ARTIFICIAL O TRANSFERENCIA DE OVULO FECUNDADO NO CONSENTIDA',
  },
  { id: '37', nombre: 'EVENTO ADVERSO EN SALUD' },
  { id: '38', nombre: 'ENFERMEDAD GENERAL' },
  { id: '39', nombre: 'ENFERMEDAD LABORAL' },
  {
    id: '40',
    nombre:
      'PROMOCION Y MANTENIMIENTO DE LA SALUD - INTERVENCIONES INDIVIDUALES',
  },
  { id: '41', nombre: 'INTERVENCION COLECTIVA' },
  { id: '42', nombre: 'ATENCION DE POBLACION MATERNO PERINATAL' },
  { id: '43', nombre: 'RIESGO AMBIENTAL' },
  { id: '44', nombre: 'OTROS EVENTOS CATASTROFICOS' },
  { id: '45', nombre: 'ACCIDENTE DE MINA ANTIPERSONAL - MAP' },
  { id: '46', nombre: 'ACCIDENTE DE ARTEFACTO EXPLOSIVO IMPROVISADO - AEI' },
  { id: '47', nombre: 'ACCIDENTE DE MUNICION SIN EXPLOTAR - MUSE' },
  { id: '48', nombre: 'OTRA VICTIMA DE CONFLICTO ARMADO COLOMBIANO' },
  {
    id: '49',
    nombre:
      'IVE POR DECISION O MANIFESTACION DE VOLUNTAD DE LA PERSONA GESTANTE HASTA LA SEMANA 24 DE GESTACION',
  },
];

export const RIPS_AMBITOS_REALIZACION: CatalogoItem[] = [
  { id: '1', nombre: 'AMBULATORIO' },
  { id: '2', nombre: 'HOSPITALARIO' },
  { id: '3', nombre: 'URGENCIAS' },
  { id: '4', nombre: 'DOMICILIARIO' },
  { id: '5', nombre: 'OTRO' },
];

export const RIPS_FINALIDADES_PROCEDIMIENTO: CatalogoItem[] = [
  { id: '01', nombre: 'DIAGNÓSTICO' },
  { id: '02', nombre: 'TERAPÉUTICO' },
  { id: '03', nombre: 'PROTECCIÓN ESPECÍFICA' },
  { id: '04', nombre: 'DETECCIÓN TEMPRANA DE ENFERMEDAD GENERAL' },
  { id: '05', nombre: 'DETECCIÓN TEMPRANA DE ENFERMEDAD PROFESIONAL' },
];

export const RIPS_PERSONAL_QUE_ATIENDE: CatalogoItem[] = [
  { id: '01', nombre: 'MÉDICO (A) ESPECIALISTA' },
  { id: '02', nombre: 'MÉDICO (A) GENERAL' },
  { id: '03', nombre: 'ENFERMERA (O)' },
  { id: '04', nombre: 'AUXILIAR DE ENFERMERÍA' },
  { id: '05', nombre: 'OTRO PROFESIONAL' },
];

export const RIPS_FORMA_REALIZACION_ACTO_QUIR: CatalogoItem[] = [
  { id: '1', nombre: 'UNICO O UNILATERAL' },
  {
    id: '2',
    nombre: 'MULTIPLE O BILATERAL, MISMA VIA, DIFERENTE ESPECIALIDAD',
  },
  {
    id: '3',
    nombre: 'MULTIPLE O BILATERAL, MISMA VIA, IGUAL ESPECIALIDAD',
  },
  {
    id: '4',
    nombre: 'MULTIPLE O BILATERAL, DIFERENTE VIA, DIFERENTE ESPECIALIDAD',
  },
  {
    id: '5',
    nombre: 'MULTIPLE O BILATERAL, DIFERENTE VIA, IGUAL ESPECIALIDAD',
  },
];
