# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - rydentclient

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present -- --c production

      - name: Copy web.config to dist directory
        run: cp src/web.config dist/cliente-angular/browser/

      - name: Copy proxy to dist directory
        run: cp proxy.conf.json dist/cliente-angular/browser/

      
      - name: Compress artifact
        run: |
          cd dist/cliente-angular/browser && 7z a -r ../../../build-artifact.zip *
        if: always()

      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: build-artifact.zip

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BB10ACCB52D048E48F08A20E376A75CD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FE069E6C4BDC4BD794B85DF9451C7E5D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5FFC46A164234605BB4BDCB37E7EF2FF }}



      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'rydentclient'
          slot-name: 'Production'
          package: build-artifact.zip
          
